# Advanced basics {.unnumbered}

[Slides]({{< var base_url>}}slides/week03/slides.html){.btn .btn-outline-primary .btn role="button"} 
[Slides PDF]({{< var base_url>}}slides/week03/slides.pdf){.btn .btn-outline-secondary .btn role="button"} 

## Interpolating
We have seen in the first class how to coarse-grain a time series. 
The other way around, sometimes, the sampling is too coarse for my purpose.

**Question:** Can I split each time step into finer ones?

The answer is yes, but with care.

Of course, we cannot create measurements out of the blue.
However, there are various ways to fill the gaps with reasonable guesses.
This is called **interpolation**.

### Linear interpolation
The most intuitive interpolation is the linear one.
Basically, it boils down to drawing a strait line between two known measurements and assume the time steps in between fall on this line.

Let us get back to our penicillin bioreactor data set. 
For the sake of the exercise, we focus on the temperature of batch nr. 1.

```{pyodide}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('https://dls.hevs.ch/ts/files/penicillin-data-01.csv')
data1 = data.loc[data['Batch ID'] == 1,['Time (h)','Temperature(T:K)']]
data1.head()
```

Currently, the time step in 0.2 hours, i.e., 12 minutes.
Let us change this time step to 5 minutes.

Keeping the first time step unchanged, the new time steps are
$$(0.2, 0.283, 0.367,0.45,0.533,...)\, .$$

```{pyodide}
# Build the array of new time steps, keeping the first time step unchanged.
new_time = np.arange(data1['Time (h)'].iloc[0],data1['Time (h)'].iloc[-1],1/12)
```

To interpolate at time $t$, we need to draw the line between the two closest measured points $t_0\leq t\leq t_1$. 
The equation of this line is (see *Algèbre Linéraire 1*)
$$ T(t) = \frac{T(t_1)-T(t_0)}{t_1-t_0}(t-t_0) + T(t_0)\, .$$
It is the easy to compute the temperature that we should use at our new time $t$.

```{pyodide}
# We first need the coordinates (time and temperature) of the two closest data points.
t = new_time[1]
t0 = data1['Time (h)'].loc[data1['Time (h)'] < t].max()
t1 = data1['Time (h)'].loc[data1['Time (h)'] > t].min()
temp0 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t0].iloc[0]
temp1 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t1].iloc[0]

# Show the linear interpolation
fig, ax = plt.subplots()
ax.plot([t0,t1],[temp0,temp1],'-o',label='original data')
ax.set_xlabel('t (h)')
ax.set_ylabel('Temperature')

# Compute the temperature at the new time step
temp = (temp1-temp0)/(t1-t0)*(t-t0) + temp0

ax.plot(t,temp,"o",label='interpolated data')

ax.legend()
plt.show()
```

We can now repeat the process for a more data points.

```{pyodide}
# Initialize the new list of temperatures with first measured value
new_temp = [data1['Temperature(T:K)'].iloc[0],]

# We begin with 8 data points
for t in new_time[1:8]:
 t0 = data1['Time (h)'].loc[data1['Time (h)'] < t].max()
 t1 = data1['Time (h)'].loc[data1['Time (h)'] > t].min()
 temp0 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t0].iloc[0]
 temp1 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t1].iloc[0]

 temp = (temp1-temp0)/(t1-t0)*(t-t0) + temp0

 new_temp.append(temp)

fig,ax = plt.subplots()

ax.plot(data1['Time (h)'].iloc[0:4],data1['Temperature(T:K)'].iloc[0:4],'-o',label='original data')
ax.plot(new_time[0:8],new_temp,'o',label='interpolated data')
ax.set_xlabel('t (h)')
ax.set_ylabel('Temperature')
plt.legend()
plt.show()
```

And we can easily do it for all data points in the time series.

### Built-in resampling function
In Python, the `pandas` library has a built-in `resample` function. 
However, it requires that time steps are in `DatetimeIndex` format, which is not the case in our time series. 
So far, the time is measured as a float and the index are integers. 

Let us fix that.

```{pyodide}
# Change the time field (which is of type 'float') to a DateTime type.
data1['Time (h)'] = pd.to_timedelta(data1['Time (h)'], unit='h')

# Create a new DataFrame whose indices are time steps.
data2 = data1[['Temperature(T:K)']].set_index(data1['Time (h)'])
```

We can now use the `resample()` function. 
If we are **downsamping**, i.e., reducing the number of data points, we need to specify how to aggregate the data. 

```{pyodide}
# Downsampling to daily value
data2_mean = data2.resample('D').mean()
data2_mean.head()

data2_median = data2.resample('D').median()
data2_median.head()

data2_max = data2.resample('D').max()
data2_max.head()

# Day numbering for the x-axis
x_days = data2_mean.index.total_seconds()/3600/24

fig,ax = plt.subplots()

# Plot vertical lines between days
day_index = data2.index[data2.index.total_seconds() % (3600*24) == 0.0]
for t in day_index:
 tf = t.total_seconds()/3600/24
 ax.plot([tf,tf],[data2.min(),data2.max()],'--',color=(.8,.8,.8))

# Plot the original data
ax.plot(data2.index.total_seconds()/3600/24,data2,color=(.7,.7,.7),label='orginial data')

# Plot the coarse grained data
ax.plot(x_days,data2_mean,'o',label='mean')
ax.plot(x_days,data2_median,'o',label='median')
ax.plot(x_days,data2_max,'o',label='max')

ax.set_xlabel('Time (days)')
ax.set_ylabel('Daily temperature')
ax.legend()

plt.show()
```

If we are **upsampling**, i.e., increasing the number of data points, the `resample` function will put `NaN` at unmeasured time steps.

```{pyodide}
data_5min = data2.resample('5min').asfreq()
data_5min.head(20)
```

There are various ways to fill these gaps, i.e., **interpolate**. 
The approprate one is problem-dependent and needs to be chosen by the user (you).

```{pyodide}
# Resampling...
data_5min = data2.resample('5min')

#...with different methods
data_5min_lin = data_5min.interpolate(method='linear')
data_5min_time = data_5min.interpolate(method='time')
data_5min_ff = data_5min.ffill()

# Using minutes as units
x_12min = data2.index.total_seconds()/60
x_5min = data_5min_lin.index.total_seconds()/60

fig,ax = plt.subplots()

ax.plot(x_12min[0:10],data2.iloc[0:10],'-o',label='original data')
ax.plot(x_5min[0:20],data_5min_lin.iloc[0:20],'o',label='linear')
ax.plot(x_5min[0:20],data_5min_time.iloc[0:20],'o',label='time')
ax.plot(x_5min[0:20],data_5min_ff.iloc[0:20],'o',label='ffill')

ax.set_xlabel('t (min)')
ax.set_ylabel('Temperature')
ax.legend()

plt.show()
```

## Smoothing
In order to mitigate noise in a signal, one may want to smooth it in post-processing.

### Sliding average
The most intuitive way to smooth a time series is to apply a **moving average**.
Namely, given a time series $X=(x_0,x_1,...,x_{N-1})$, one chooses a window size $T\in\mathbb{N}$ and computes a new time series $Y$, where
$$ y_i = \frac{1}{2T+1}\sum_{k=-T}^{T}x_{i+k}\, .$$
Notice that in the smoothing process, we loose some information.
The new time series $Y$ starts at time step $T$ and ends at time step $N-T-1$.

**TODO: Illustrate the moving average with a rectangular window.**

### Sliding window
Sometimes, one may want to smooth a signal, but give more weight to some time steps than others.
In this case, we use more fancy windows for the moving average.

**TODO: Illustrate different windows.**


## Stationarity
In this course, we will assume that the processes we study are **stationary**, i.e., their statistical characteristics remain constant over time.
In a stationary process, mean and variance remain consant over time.

    Example: ...

When a process is not stationary, there are some techniques to preprocess the data and make it stationary.

### Seasonality
Typically, the ACF can be used to detect any seasonality in a time series.

**Seasonality** in a time series is a recurring, periodic behavior.

    Example:
    There is obviously seasonality in the daily temperature measurements at an outdoor location.
    In this case, the seasonality period is one year.

## Autocorrelation function (ACF)
The **autocorrelation function (ACF)** computes the correlation of a time series with itself after a given time lag $\tau$.
Given a time series $X=(x_0,x_1,x_2,...)$, let us define the shifted time series $X_{\tau}=(x_{\tau},x_{\tau+1},x_{\tau+2},...)$.
Then the ACF of $X$ at time lag $\tau$ is
$$ \mathrm{ACF}_X(\tau) = r_{X,X_{\tau}} = \frac{\mathrm{cov}(X,X_{\tau})}{\sigma_X^2} = \frac{\sum_{i=0}^{N-\tau-1}(x_i-\mu_X)(x_{i+\tau}-\mu_X)}{\sigma_X^2}\, .$$

**Remarks:**
- Notice that we assumed stationarity because the mean $\mu_X$ is the same for any value of the time lag $\tau$.
- We had to truncate the summation to $N-\tau-1$ to accommodate for the time lag.

**TODO: Examples of computation, illustration, and interpretation.**


## Hands on






