---
title: "Applied Statistics: Time Series"
subtitle: "Advanced basics"
format:
 live-revealjs:
  slide-number: true
  brand: ../_brand.yml
  theme: ../hevs.scss
  show-slide-number: all
  preview-links: auto
  chalkboard: true
  logo: Https://www.hevs.ch/_nuxt/img/logo_hesso.9af1d79.svg
  footer: "[Time Series](https://dls.hevs.ch/ts/week03/)"
---

## Interpolating
Sometimes, we want to reduce the length of a time step. 

**Question:** Can I split each time step into finer ones?

The answer is yes, but with care.
This is called **interpolation**.

## Linear interpolation
The most intuitive interpolation is the linear one.

```{pyodide}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('https://dls.hevs.ch/ts/files/penicillin-data-01.csv')
data1 = data.loc[data['Batch ID'] == 1,['Time (h)','Temperature(T:K)']]
data1.head()
```

## Linear interpolation
From 12 minutes, we want 5 minutes.

Keeping the first time step unchanged, the new time steps are
$$(0.2, 0.283, 0.367,0.45,0.533,...)\, .$$

```{pyodide}
# Build the array of new time steps, keeping the first time step unchanged.
new_time = np.arange(data1['Time (h)'].iloc[0],data1['Time (h)'].iloc[-1],1/12)
```

## Linear interpolation
We need to draw the line between the two closest measured points $t_0\leq t\leq t_1$:
$$ T(t) = \frac{T(t_1)-T(t_0)}{t_1-t_0}(t-t_0) + T(t_0)\, .$$

```{pyodide}
# We first need the coordinates (time and temperature) of the two closest data points.
t = new_time[1]
t0 = data1['Time (h)'].loc[data1['Time (h)'] < t].max()
t1 = data1['Time (h)'].loc[data1['Time (h)'] > t].min()
temp0 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t0].iloc[0]
temp1 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t1].iloc[0]

# Show the linear interpolation
fig, ax = plt.subplots()
ax.plot([t0,t1],[temp0,temp1],'-o',label='original data')
ax.set_xlabel('t (h)')
ax.set_ylabel('Temperature')

# Compute the temperature at the new time step
temp = (temp1-temp0)/(t1-t0)*(t-t0) + temp0

ax.plot(t,temp,"o",label='interpolated data')

ax.legend()
plt.show()
```

## Lineare interpolation
We can now repeat the process for a more data points.

```{pyodide}
# Initialize the new list of temperatures with first measured value
new_temp = [data1['Temperature(T:K)'].iloc[0],]

# We begin with 8 data points
for t in new_time[1:8]:
 t0 = data1['Time (h)'].loc[data1['Time (h)'] < t].max()
 t1 = data1['Time (h)'].loc[data1['Time (h)'] > t].min()
 temp0 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t0].iloc[0]
 temp1 = data1['Temperature(T:K)'].loc[data1['Time (h)'] == t1].iloc[0]

 temp = (temp1-temp0)/(t1-t0)*(t-t0) + temp0

 new_temp.append(temp)

fig,ax = plt.subplots()

ax.plot(data1['Time (h)'].iloc[0:4],data1['Temperature(T:K)'].iloc[0:4],'-o',label='original data')
ax.plot(new_time[0:8],new_temp,'o',label='interpolated data')
ax.set_xlabel('t (h)')
ax.set_ylabel('Temperature')
plt.legend()
plt.show()
```


## Built-in resampling function
`pandas` has a built-in `resample` function. 

But it requires that time steps are in `DatetimeIndex` format. 

```{pyodide}
# Change the time field (which is of type 'float') to a DateTime type.
data1['Time (h)'] = pd.to_timedelta(data1['Time (h)'], unit='h')

# Create a new DataFrame whose indices are time steps.
data2 = data1[['Temperature(T:K)']].set_index(data1['Time (h)'])
```

## Downsampling
We can now use the `resample()` function. 

For **downsamping**, we need to specify how to aggregate the data. 

```{pyodide}
# Downsampling to daily value
data2_mean = data2.resample('D').mean()
data2_mean.head()

data2_median = data2.resample('D').median()
data2_median.head()

data2_max = data2.resample('D').max()
data2_max.head()

# Day numbering for the x-axis
x_days = data2_mean.index.total_seconds()/3600/24

fig,ax = plt.subplots()

# Plot vertical lines between days
day_index = data2.index[data2.index.total_seconds() % (3600*24) == 0.0]
for t in day_index:
 tf = t.total_seconds()/3600/24
 ax.plot([tf,tf],[data2.min(),data2.max()],'--',color=(.8,.8,.8))

# Plot the original data
ax.plot(data2.index.total_seconds()/3600/24,data2,color=(.7,.7,.7),label='orginial data')

# Plot the coarse grained data
ax.plot(x_days,data2_mean,'o',label='mean')
ax.plot(x_days,data2_median,'o',label='median')
ax.plot(x_days,data2_max,'o',label='max')

ax.set_xlabel('Time (days)')
ax.set_ylabel('Daily temperature')
ax.legend()

plt.show()
```

## Upsampling
For **upsampling**, the `resample` function will put `NaN` at unmeasured time steps.

```{pyodide}
data_5min = data2.resample('5min').asfreq()
data_5min.head(20)
```

There are various ways to **interpolate** these gaps

```{pyodide}
# Resampling...
data_5min = data2.resample('5min')

#...with different methods
data_5min_lin = data_5min.interpolate(method='linear')
data_5min_time = data_5min.interpolate(method='time')
data_5min_ff = data_5min.ffill()

# Using minutes as units
x_12min = data2.index.total_seconds()/60
x_5min = data_5min_lin.index.total_seconds()/60

fig,ax = plt.subplots()

ax.plot(x_12min[0:10],data2.iloc[0:10],'-o',label='original data')
ax.plot(x_5min[0:20],data_5min_lin.iloc[0:20],'o',label='linear')
ax.plot(x_5min[0:20],data_5min_time.iloc[0:20],'o',label='time')
ax.plot(x_5min[0:20],data_5min_ff.iloc[0:20],'o',label='ffill')

ax.set_xlabel('t (min)')
ax.set_ylabel('Temperature')
ax.legend()

plt.show()
```

## Moving average
The most intuitive way to smooth a time series.

Given a time series $X=(x_0,x_1,...,x_{N-1})$ and a window size $T\in\mathbb{N}$, the moving average time series $Y$ is 
$$ y_i = \frac{1}{T}\sum_{k=-T/2}^{T/2-1}x_{i+k}\, .$$


```{pyodide}
fig, ax = plt.subplots(figsize=(8,6))

T = 10 # window size
i = 6 # one time step
t = data2.index[i].total_seconds()/3600
i0 = i-int(T/2) # first step in the MA
t0 = data2.index[i0].total_seconds()/3600
i1 = i+int(T/2)-1 # last step in the MA
t1 = data2.index[i1].total_seconds()/3600
x = data2.iloc[i0:i1,0]
y = x.mean()

mi = data2.iloc[:20].min()
ma = data2.iloc[:20].max()

ax.fill([t0,t1,t1,t0], [mi,mi,ma,ma], color='C1', alpha=.2, label='averaging window')
ax.plot(data2.index[:20].total_seconds()/3600, data2.iloc[:20], '-o', label='original data')
ax.plot(t,y,'o',label='average value')

ax.set_xlabel('t (h)')
ax.set_ylabel('Temperature')
ax.legend()

plt.show()
```

## Moving average
The resulting time series is smoother. 

The longer the window, the smoother the time series.

```{pyodide}
fig, ax = plt.subplots(figsize=(7,4))

T = 10 # window size
y = []
for i in range(5,15):
 t = data2.index[i].total_seconds()/3600
 i0 = i-int(T/2) # first step in the MA
 i1 = i+int(T/2)-1 # last step in the MA
 y.append(data2.iloc[i0:i1,0].mean())

ax.plot(data2.index[:20].total_seconds()/3600, data2.iloc[:20], '-o', label='original data')
ax.plot(data2.index[range(5,15)].total_seconds()/3600,y,'o',label='moving average')

ax.set_xlabel('t (h)')
ax.set_ylabel('Temperature')
ax.legend()

plt.show()
```

## Built-in MA
Of course, there is a built-in tool to compute a moving average in `pandas`.

```{pyodide}
data1['moving average'] = data1['Temperature(T:K)'].rolling(window=10).mean()

fig, ax = plt.subplots(figsize=(7,4))

ax.plot(data1['Time (h)'],data1['Temperature(T:K)'])
ax.plot(data1['Time (h)'],data1['moving average'])

ax.set_xlabel('t (h)')
ax.set_ylabel('temperature')

plt.show()
```

## Sliding window
There are more fancy ways to compute an moving average. 

Let $W=(w_{-T/2},w_{-T/2+1},...,w_{-1},w_0,w_1,...,w_{T/2-1})$ be a list of weights. 

The moving average of time series $X$ with window $W$ is the time series $Y=(y_{T/2},y_{T/2+1},...)$ where
$$ y_i = \sum_{k=-T/2}^{T/2-1} w_{k}x_{i+k}\, . $$

## Sliding window

```{pyodide}
# SciPy is a nice library for building windows
from scipy.signal.windows import get_window

l = 10 # window size

# Examples of window names: 'triang', 'hamming', 'hanning', 'blackman', ('gaussian',std), ('exponential',lambda).
win_name = 'hamming'

w = get_window(win_name,l)
data1['windowed'] = data1['Temperature(T:K)'].rolling(l).apply(
 lambda x: np.dot(x,w) / w.sum(), raw=True
)

fig, (ax1,ax2) = plt.subplots(nrows=2,figsize=(7,6))

ax1.plot(w,'-o')
ax1.set_xlabel('idx')
ax1.set_ylabel('w')

ax2.plot(data1['Time (h)'],data1['Temperature(T:K)'],label='raw data')
ax2.plot(data1['Time (h)'],data1['windowed'],label='windowed with '+win_name)
ax2.set_xlabel('t (h)')
ax2.set_ylabel('T (K)')
ax2.legend()

plt.show()
```

## Stationarity
Processes are assumed **stationary**, i.e., their statistical characteristics remain constant over time.

    Example: For humans, the heart rate (which is a time series) changes depending on the person's age or state of conciousness. 
    We do not expect to observe the same heart rate if measure on a child or on an adult, on someone awake or someone asleep. 
    Therefore, on the scale of years or of days, the heart rate is not a stationary process. 


## Autocorrelation function (ACF)
The **autocorrelation function (ACF)** computes the correlation of a time series with itself after a given time lag $\tau$.

Let $X=(x_0,x_1,x_2,...)$ and define the shifted time series $X_{\tau}=(x_{\tau},x_{\tau+1},x_{\tau+2},...)$.

Then the ACF of $X$ at time lag $\tau$ is
$$ \mathrm{ACF}_X(\tau) = r_{X,X_{\tau}} = \frac{\mathrm{cov}(X,X_{\tau})}{\sigma_X^2} = \frac{\sum_{i=0}^{N-\tau-1}(x_i-\mu_X)(x_{i+\tau}-\mu_X)}{\sigma_X^2}\, .$$

## Autocorrelation function (ACF)

**Correlation** quantifies the similarity between two time series. 

 Example: 
 The website [spurious correlations](https://www.tylervigen.com/spurious-correlations) highlights some time series that look very similar, but do not have any relation with each other.

The autocorrelation quantifies to what extent a time series *"looks like itself later in time"*. 

## Weather data
We will highlight the ACF with a weather time series: [daily average temperature in Sion, from January 2000 to December 2021](https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/sio/ogd-smn_sio_d_historical.csv)

```{pyodide}
df = pd.read_csv('https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/sio/ogd-smn_sio_d_historical.csv', delimiter=';').iloc[range(16985,25021),[1,2]]
df.head()
```

## Computing the ACF
What do you expect?

```{pyodide}
acf_df = [df['tre200d0'].autocorr(lag=tau) for tau in range(1,4000)]

fig, ax = plt.subplots(figsize=(7,4))
ax.plot(acf_df)
ax.set_xlabel('tau (days)')
ax.set_ylabel('ACF')

plt.show()
```
Maximum every 365 time steps, i.e., every year. 

## Time lag
Let us look at the time series and its lagged version

```{pyodide}
fig, ax = plt.subplots(figsize=(7,4))

lag = 10
ax.plot(df['tre200d0'].iloc[range(0,1000)], label='original time series')
ax.plot(df['tre200d0'].iloc[range(lag,1000+lag)], label='lagged time series (lag = '+str(lag)+')', alpha=.5)

ax.set_xlabel('time (days)')
ax.set_ylabel('temperature')
ax. legend()

plt.show()
```

## Seasonality or periodicity
The ACF can detect seasonality or periodicity in a time series.

**Seasonality or perioditicty** in a time series is a recurring, periodic behavior.

    Example:
    There is obviously yearly seasonality in the daily temperature measurements at an outdoor location.
    In this case, the seasonality period is one year.

    There is also a daily periodicity in the electricity consumption of a household, whose behavior is strongly correlated with the hour of the day.


## Hands on

See [webpage](https://dls.hevs.ch/ts/week03/).



