project:
  type: book
  output-dir: _book
  post-render: quarto render --profile slides

number-depth: 1

book:
  reader-mode: false
  title: "Applied Statistics: Time Series"
  chapters:
    - index.qmd
    - part: "Course 1"
      chapters:
        - week00/index.qmd
        - week01/index.qmd
    - part: "Course 2"
      chapters:
        - week02/index.qmd
    - part: "Course 3"
      chapters:
        - week03/index.qmd
    - part: "Course 4"
    - part: "Course 5"
    - part: "Course 6"
    - part: "Course 7"
    - part: "Course 8"
    - part: "Course 9"
    - part: "Course 10"
    - part: "Course 11"
    - part: "Course 12"
    - part: "Course 13"
    - part: "Course 14"
    - part: "Course 15"

format:
  live-html:
    include-after-body: _includes/dls-menu.html
    theme: cosmo
  pdf:
    documentclass: scrreprt
