# Recap of statistics {.unnumbered}

[Slides]({{< var base_url>}}slides/week02/slides.html){.btn .btn-outline-primary .btn role="button"} 
[Slides PDF]({{< var base_url>}}slides/week02/slides.pdf){.btn .btn-outline-secondary .btn role="button"} 


Throughout this class, we will need some standard tools from statistics.
We recall here some definitions with examples.

## Statistics
The goal of statistics is to provide a summarized description of a (large) set of values.
As raw data, a large set of measurement can be hard to parse.
Statistics are an attempt to help humans parse large, complex set of values.

Of course, no statistics can replace the aforementioned set of values and is merely a partial, biased summary thereof.
Nevertheless, an appropriate use of statistical tools can help extract crucial informations from these data sets.

### Example data set
We will again use our [bioreactor time series](../files/penicillin-data-01.csv)

```{pyodide}
import pandas as pd

data = pd.read_csv('https://dls.hevs.ch/ts/files/penicillin-data-01.csv')
data.describe()
```

```{pyodide}
subdata = data.loc[data["Batch ID"]==2,"pH(pH:pH)"]
subdata.describe()
```

```{pyodide}
import matplotlib.pyplot as plt

ax = subdata.hist(bins=50)
ax.set_xlabel("pH")
ax.set_ylabel("occurence")

plt.show()
```


### Mean and variance
Given a set of values $X = (x_0,x_1,x_2,...,x_{N-1})$, the **mean** of $X$ is
$$ \mathrm{mean}(X) = \mu_X = \langle X\rangle = \frac{1}{N}\sum_{i=0}^{N-1}x_i\, .$$
The mean value of a set is the value that would give the same total sum if each element of the set had the same value.
In a sense, the mean is the "center of mass" of a data set.

The mean is the most basic and intuitive summarizing value of a data set.

To measure the dispersion of the data around the mean, one can compute the **variance** of $X$,
$$\mathrm{var}(X) = \sigma_X^2 = \langle (X - \langle X\rangle)^2\rangle = \frac{1}{N}\sum_{i=0}^{N-1} \left(x_i - \mu_X\right)^2\, .$$

The square root of the variance is the **standard deviation**.

```{pyodide}
import numpy as np

mu = subdata.describe()["mean"]
sig = subdata.describe()["std"]

ax = subdata.hist(bins=49)

max_val = np.histogram(subdata,bins=50)[0].max()
ax.plot([mu,mu],[0,1.1*max_val],"--",color="C1",lw=2)
ax.fill([mu-sig,mu+sig,mu+sig,mu-sig],[0,0,1.1*max_val,1.1*max_val],color="C1",alpha=.2)

ax.set_xlabel("pH")
ax.set_ylabel("occurence")

plt.show()
```

### Strength
- Very intuitive
- Easy to compute

### Weakness
- Very sensitive to extreme values

### Median and quantiles
While the mean represents the center of mass of a data set, the median attempts to represent the "middle" of the data set.
The **median** $m$ is the value such that half of the samples are larger than $m$ and the other half are smaller.

To compute the median, let us renumber the elements of $X$ such they are ordered in increasing order.
Then
$$\mathrm{median}(X) = \left\{\begin{array}{ll}
    x_{(N-1)/2} & \text{if } N \text{ is odd,} \\
    (x_{N/2-1}+x_{N/2})/2 & \text{if } N \text{ is even.}
\end{array}\right.$$

The concept of **quantiles** generalizes the notion of median.
Given $\rho\in[0,1]$ the $\rho$-th quantile of $X$, written $q_\rho(X)$ is the value that is larger than a proportion $\rho$ of the samples.

```{pyodide}
import numpy as np

ax = subdata.hist(bins=50)

q00 = subdata.describe()["min"]
q25 = subdata.describe()["25%"]
q50 = subdata.describe()["50%"]
q75 = subdata.describe()["75%"]
q100 = subdata.describe()["max"]
max_val = np.histogram(subdata,bins=50)[0].max()

ax.plot([q50,q50],[0,1.1*max_val],"--",color="C2",lw=2)
ax.fill([q25,q75,q75,q25],[0,0,1.1*max_val,1.1*max_val],color="C2",alpha=.2)
ax.fill([q00,q100,q100,q00],[0,0,1.1*max_val,1.1*max_val],color="C2",alpha=.05)

ax.set_xlabel("pH")
ax.set_ylabel("occurence")

plt.show()
```

In particular,
- $q_{0.5}(X) = \mathrm{median}(X)$
- $q_{0}(X) = \mathrm{min}(X)$
- $q_{1}(X) = \mathrm{max}(X)$

### Special cases
The five **quartiles** $(q_0, q_{0.25}, q_{0.5}, q_{0.75}, q_1)$ divide the samples into four groups of same cardinality.
The difference $q_{0.75}-q_{0.25}$ is called the **interquartile range (IQR)**.

The 101 percentiles $(q_0, q_{0.01}, q_{0.02},..., q_{0.99}, q_1)$ divide the samples into 100 groups of same cardinality.


### Box plot
In 1970, [John Tukey](https://en.wikipedia.org/wiki/John_Tukey) introduced the **box plot** as we know it today, extending the work of [Mary Eleanor Spear](https://en.wikipedia.org/wiki/Mary_Eleanor_Spear).
The strength of the box plot is that it represents a lot of information in a very compact graphical way.

A box plot is represented along the axis of values taken by the samples.
It is composed of:

- A rectangle (the box itself) filling the space between the first ($q_{0.25}$) and third ($q_{0.75}$) quartiles.
- A bold line at the median of the sample.
- Whiskers that run from the side of the box to the largest sample value that is smaller than $q_{0.75}+1.5\cdot\mathrm{IQR}$ (resp. larger than $q_{0.25}-1.5\cdot\mathrm{IQR}$).
- Dots at **outlier** values, namely, values that are larger than $q_{0.75}+1.5\cdot\mathrm{IQR}$ (resp. smaller than $q_{0.25}-1.5\cdot\mathrm{IQR}$).

```{pyodide}
fig, (ax1,ax2) = plt.subplot(nrows=2, sharex=True, gridspec_kw={'height_ratios': (1,4)})

ax1.boxplot(subdata, orientation='horizontal', widths=.6)
ax1.set(yticks=[])

ax2.hist(subdata, bins=50)

ax1.spines['bottom'].set_visible(False)
ax1.tick_params(bottom=False)
ax2.spines['top'].set_visible(False)

plt.tight_layout()
plt.show()
```

### Covariance
Given two time series $X$ and $Y$ with the **same time steps**, their **covariance** quantifies their shared variability.
In other words, the larger the covariance, the more similar the time series.
The covariance is computed as
$$ \mathrm{cov}(X,Y) =  \langle(X - \mu_X)(Y - \mu_Y)\rangle = \frac{1}{N}\sum_{i=0}^{N-1} \left(x_i - \mu_X\right)\left(y_i - \mu_Y\right)\, . $$
In particular, if the time series are normalized to zero-mean, the covariance reduces to
$$ \mathrm{cov}(X,Y) = \frac{1}{N}\sum_{i=0}^{N-1}x_iy_i\, .$$

The problem with covariance is that it is an absolute quantity, i.e., covariances are hard to compare.

```{pyodide}
data.cov()
```

### Correlation
This problem is solved with the **correlation** which considers normalized time series.
The **Pearson correlation coefficient** of two time series $X$ and $Y$ is
$$ r_{XY} = \frac{\sum_{i=0}^{N-1}(x_i-\mu_X)(y_i-\mu_Y)}{\sqrt{\sum_{i=0}^{N-1}(x_i-\mu_X)^2}\sqrt{\sum_{i=0}^{N-1}(y_i-\mu_Y)^2}} = \frac{\mathrm{cov}(X,Y)}{\sigma_X\sigma_Y}\, .$$

The correlation coefficient takes value between $-1$ and $1$.
A value of $1$ (resp. $-1$) indicates two perfectly correlated (resp. anticorrelated) time series, i.e., knowing the value of one time series fully informs about the value of the other.
A correlation coefficient of $0$ indicates that the two time series are completely independent.

```{pyodide}
r = data.corr()
print(r)

fig, ax = plt.subplots()
rax = ax.matshow(r, cmap='coolwarm', vmin=-1, vmax=1)
fig.colorbar(rax)

ax.set_yticks(range(len(r.columns)))
ax.set_yticklabels(r.columns)

plt.show()
```


## Hands on

Use again our [penicillin data set](../files/penicillin-data-01.csv).

1. What is the batch with maximal average temperature?

1. Is this batch's temperature time series really exceptional compared to the others? Justify.
   
   1. Find the batch whose average temperature is the most "central" one.
   
   1. Compare the distribution of temperature between theses two batches (e.g., with a histogram or a box plot).

   1. What can you see?

1. Do the same with the batch with lowest average temperature.
   What changes?

1. In theses samples, is there a correlation between concentration and pH? Between concentration and temperature? Between pH and temperature?

1. Is it expected?

1. Among the other quantities in the [original data set](http://www.industrialpenicillinsimulation.com/) is there one where you expect to see a correlation with the penicillin concentration? 
   Justify.

1. (Optional) Test your prediction by importing the data and computing the correlation.




